### PR TITLE
Properly detect opening of Serial port by host

### PR DESCRIPTION
**Pull request by bigdinotech**
-fix issue of incorrect intial value of host_open causing !Serial on the
corelibs to not work as expected
-some improvements in relibility of uploading sketches
-some code refactoring

### CODE REVIEW

**Comment by bigdinotech** [comment]
@eriknyquist @SidLeung ready for review

**Comment by eriknyquist** [comment]
looks good, +1

**Comment by bigdinotech** [comment]
@eriknyquist added a fix for the Serial1 Serial issue
@SidLeung @eriknyquist ready for review

**Comment by bigdinotech** [comment]
@calvinatintel please merge

**Comment by calvinatintel** [comment]
There are two commits. Do you want to squash or keep it as is?

**Comment by bigdinotech** [comment]
just keep it as is

**Pull request merged**
